
# Configuration settings
spring:
  data:
    mongodb:
      database: mongo_demo
      authentication-database: admin
      username: root
      password: hproot
      port: 27017
      host: localhost